'use client'

// ── lib/hooks/useLang.tsx ───────────────────────────────────────
// LangProvider + useLang() — powers every t("...") call across the
// app (Nav, home page, tool pages, and any hub you wire in later).
//
// Built from the CHRONOS monolith's full DICT (chronos-v2-patched-12,
// via the CoreRegistry partition bundle) — every nav/footer/category/
// tool string in EN + FR lives in DICT below.

import React, { createContext, useContext, useState, useEffect, useCallback } from 'react'

type Lang = 'en' | 'fr'

const DICT = {
  en: {
    "home.headline": "Everything You Need.",
    "home.headlineSub": "One Powerful Toolkit.",
    "home.description": "Free online tools. No sign-up required.",
    "nav.pdfTools": "PDF Tools",
    "nav.imageTools": "Image Tools",
    "nav.calculators": "Calculators",
    "nav.converters": "Converters",
    "nav.network": "Network",
    "nav.allTools": "All Tools",
    "nav.searchTools": "Search tools",
    "nav.commandPalette": "Command Palette (Ctrl+K)",
    "nav.switchToLight": "Switch to light mode",
    "nav.switchToDark": "Switch to dark mode",
    "nav.openMenu": "Open menu",
    "nav.closeMenu": "Close menu",
    "nav.search": "Search",
    "nav.lightMode": "Light mode",
    "nav.darkMode": "Dark mode",
    "nav.language": "Language",

    "search.placeholder": "Search tools, converters, calculators...",
    "search.clear": "Clear search",
    "search.noResults": "No results for",
    "search.results": "Search results",

    "palette.placeholder": "Search tools, converters, calculators...",
    "palette.recentAndActions": "Recent & Quick Actions",
    "palette.results": "results",
    "palette.noToolsFound": "No tools found for",
    "palette.tryDifferentKeyword": "Try a different keyword",
    "palette.quickAction": "Quick action",
    "palette.favorite": "favorite",
    "palette.recentlyUsed": "recently used",
    "palette.usedTimes": "used {n} times",
    "palette.fav": "Fav",
    "palette.recent": "Recent",
    "palette.removeFromFavorites": "Remove {name} from favorites",
    "palette.addToFavorites": "Add {name} to favorites",
    "palette.navigate": "navigate",
    "palette.open": "open",
    "palette.close": "close",
    "palette.showTrending": "Show Trending Tools",
    "palette.showNewest": "Show Newest Tools",
    "palette.showPopular": "Show Popular Tools",
    "palette.openPdfTools": "Open PDF Tools",
    "palette.openImageTools": "Open Image Tools",
    "palette.openCalculators": "Open Calculators",
    "palette.openNetworkTools": "Open Network Tools",
    "palette.openAiWriting": "Open AI Writing",

    "toolCard.openTool": "Open tool →",
    "toolCard.nextStep": "Next step →",
    "toolCard.toolsCount": "tools →",
    "toolCard.trending": "Trending",
    "toolCard.removeFromFavorites": "Remove from favorites",
    "toolCard.addToFavorites": "Add to favorites",

    "footer.tagline": "Free online tools for everyone. No sign-up, no limits, no software needed.",
    "footer.toolsHeading": "Tools",
    "footer.resourcesHeading": "Resources",
    "footer.companyHeading": "Company",
    "footer.pdfTools": "PDF Tools",
    "footer.imageTools": "Image Tools",
    "footer.calculators": "Calculators",
    "footer.converters": "Converters",
    "footer.blog": "Blog",
    "footer.tutorials": "Tutorials",
    "footer.apiDocs": "API Docs",
    "footer.changelog": "Changelog",
    "footer.about": "About",
    "footer.privacyPolicy": "Privacy Policy",
    "footer.termsOfUse": "Terms of Use",
    "footer.contact": "Contact",
    "footer.copyright": "© 2026 CHRONOS. All rights reserved.",
    "footer.madeWith": "Made with ❤️ for the web",

    "nh.ip.title": "Your IP Address",
    "nh.ip.detecting": "Detecting...",
    "nh.ip.copy": "Copy IP",
    "nh.ip.copied": "✓ Copied!",
    "nh.ip.error": "Could not retrieve your IP address. You may be behind a VPN or firewall.",
    "nh.ip.connectionDetails": "Connection Details",
    "nh.ip.isp": "ISP / Operator",
    "nh.ip.timezone": "Timezone",
    "nh.ip.latitude": "Latitude",
    "nh.ip.longitude": "Longitude",
    "nh.ip.region": "Region",
    "nh.ip.country": "Country",
    "nh.ip.refresh": "↻ Refresh",
    "nh.history.title": "History ({n})",
    "nh.history.exportCsv": "↓ Export CSV",
    "nh.history.clear": "Clear",

    "nh.whois.title": "Whois Lookup",
    "nh.whois.placeholder": "github.com",
    "nh.whois.error": "Whois lookup failed. Try a registered domain (e.g. google.com).",
    "nh.whois.registrar": "Registrar",
    "nh.whois.dnssec": "DNSSEC",
    "nh.whois.created": "Created",
    "nh.whois.updated": "Updated",
    "nh.whois.expires": "Expires",
    "nh.whois.status": "Status",
    "nh.whois.nameservers": "Nameservers",
    "nh.whois.signed": "Signed ✓",
    "nh.whois.unsigned": "Unsigned",

    "nh.ssl.title": "SSL Certificate Checker",
    "nh.ssl.placeholder": "example.com",
    "nh.ssl.error": "SSL check failed",
    "nh.ssl.noCerts": "No certificates found",
    "nh.ssl.daysRemaining": "days remaining",
    "nh.ssl.issuer": "Issuer",
    "nh.ssl.subject": "Subject",
    "nh.ssl.validFrom": "Valid From",
    "nh.ssl.expires": "Expires",
    "nh.ssl.totalCerts": "Total Certs (CT)",
    "nh.ssl.statusValid": "VALID",
    "nh.ssl.statusExpiringSoon": "EXPIRING SOON",
    "nh.ssl.statusExpired": "EXPIRED",
    "nh.ssl.statusInvalid": "INVALID",
    "nh.ssl.historyValid": "✓ Valid",
    "nh.ssl.historyInvalid": "✗ Invalid",

    "nh.domainAge.title": "Domain Age Checker",
    "nh.domainAge.placeholder": "wikipedia.org",
    "nh.domainAge.errorNoDate": "Creation date not found for this domain.",
    "nh.domainAge.error": "Could not retrieve domain registration data.",
    "nh.domainAge.years": "Years",
    "nh.domainAge.months": "Months",
    "nh.domainAge.days": "Days",
    "nh.domainAge.trustScore": "Trust Score",
    "nh.domainAge.registered": "Registered",
    "nh.domainAge.expires": "Expires",
    "nh.domainAge.lastUpdated": "Last Updated",
    "nh.domainAge.totalDays": "Total Days",
    "nh.domainAge.trustHigh": "Highly Trusted",
    "nh.domainAge.trustEstablished": "Established",
    "nh.domainAge.trustModerate": "Moderate",
    "nh.domainAge.trustNew": "New Domain",

    "nh.speed.title": "Internet Connection Speed",
    "nh.speed.download": "Download",
    "nh.speed.ping": "Ping",
    "nh.speed.runningTest": "Running test...",
    "nh.speed.running": "Running...",
    "nh.speed.runAgain": "↻ Run Again",
    "nh.speed.startTest": "▶ Start Test",
    "nh.speed.noteTitle": "Note:",
    "nh.speed.noteBody": "This is a Speed Estimator — it downloads a test file directly from Cloudflare's edge servers and measures throughput in your browser. Results reflect real-world performance for your connection.",
    "nh.speed.logMeasuringLatency": "📡 Measuring latency (3 samples)...",
    "nh.speed.logPingResult": "✓ Ping: {ms}ms (best of 3)",
    "nh.speed.logPingUnavailable": "⚠ Ping unavailable, using estimate",
    "nh.speed.logMeasuringDownload": "⬇ Measuring download speed...",
    "nh.speed.logDownloadResult": "✓ Download: {mbps} Mbps",
    "nh.speed.logDownloadFailed": "✗ Download test failed — check your connection",
    "nh.speed.logImageFallback": "⟳ Using image timing fallback...",
    "nh.speed.ratingExcellent": "EXCELLENT",
    "nh.speed.ratingGood": "GOOD",
    "nh.speed.ratingAverage": "AVERAGE",
    "nh.speed.ratingSlow": "SLOW",
    "nh.speed.historyLabel": "↓ {download} Mbps · Ping {ping}ms · {rating}",

    "nh.status.title": "Website Status Checker",
    "nh.status.placeholder": "example.com or https://example.com",
    "nh.status.checkButton": "Check",
    "nh.status.popularSites": "Popular Services",
    "nh.status.checkAny": "Check Any Website",
    "nh.status.checkAll": "↻ Check All",
    "nh.status.prodNote": "Note: In production, checks run via a dedicated /api/check-site Vercel serverless route for accuracy. Preview uses corsproxy.io.",
    "nh.status.checking": "● Checking...",
    "nh.status.online": "● ONLINE",
    "nh.status.down": "● DOWN",
    "nh.status.idle": "○ Idle",
    "nh.status.responseTime": "Response Time",
    "nh.status.httpStatus": "HTTP Status",
    "nh.status.historyUp": "✓ Up",
    "nh.status.historyDown": "✗ Down",

    "nh.password.title": "Password Generator",
    "nh.password.copy": "Copy",
    "nh.password.copied": "✓ Copied!",
    "nh.password.length": "Length",
    "nh.password.uppercase": "Uppercase (A-Z)",
    "nh.password.lowercase": "Lowercase (a-z)",
    "nh.password.numbers": "Numbers (0-9)",
    "nh.password.symbols": "Symbols (!@#$...)",
    "nh.password.strengthWeak": "Weak",
    "nh.password.strengthFair": "Fair",
    "nh.password.strengthStrong": "Strong",
    "nh.password.strengthVeryStrong": "Very Strong",
    "nh.password.generate": "↻ Generate New",
    "nh.password.entropy": "Entropy: {bits} bits",
    "nh.password.generatedTitle": "Generated Password",
    "nh.password.generateAria": "Generate new password",
    "nh.password.passwordLength": "Password Length",
    "nh.password.characterTypes": "Character Types",
    "nh.password.generateNewBtn": "↻ Generate New Password",
    "nh.password.recentPasswords": "Recent Passwords",

    "nh.dns.title": "DNS Lookup",
    "nh.dns.placeholder": "example.com",
    "nh.dns.error": "DNS lookup failed",
    "nh.dns.recordsFor": "{type} records — {domain}",
    "nh.dns.noRecords": "No records found for this type.",
    "nh.dns.answer": "Answer",
    "nh.dns.authority": "Authority",
    "nh.dns.ttl": "TTL",
    "nh.dns.domainLabel": "Domain",
    "nh.dns.recordType": "Record Type",
    "nh.dns.lookingUp": "Looking up...",
    "nh.dns.lookupBtn": "🔍 Lookup",
    "nh.dns.nxdomain": "Domain not found (NXDOMAIN)",
    "nh.dns.errorCode": "DNS error code {code}",
    "nh.dns.authorityRecords": "AUTHORITY RECORDS",
    "nh.dns.historyLabel": "{domain} [{type}] — {count} record{plural}",

    "nh.ping.pingPopular": "Ping Popular Servers",
    "nh.ping.pingAll": "▶ Ping All",
    "nh.ping.notTested": "○ Not tested",
    "nh.ping.pinging": "● Pinging...",
    "nh.ping.unreachable": "✕ Unreachable",
    "nh.ping.qualityExcellent": "Excellent",
    "nh.ping.qualityGood": "Good",
    "nh.ping.qualityFair": "Fair",
    "nh.ping.qualityPoor": "Poor",
    "nh.ping.minMax": "min {min} / max {max}",
    "nh.ping.pingCustomHost": "Ping Custom Host",
    "nh.ping.placeholder": "example.com",
    "nh.ping.pingBtn": "Ping",
    "nh.ping.hostUnreachable": "✕ Host unreachable or blocked",
    "nh.ping.avg": "AVG",
    "nh.ping.min": "MIN",
    "nh.ping.max": "MAX",
    "nh.ping.note": "Browser ping uses HTTP timing (not ICMP) — 5 samples, reports min/avg/max.",
    "nh.ping.historyLabel": "{host} — avg {avg}ms · min {min} / max {max}",

    "nh.ports.title": "Port Scanner",
    "nh.ports.placeholder": "example.com or IP",
    "nh.ports.scanBtn": "🔌 Scan",
    "nh.ports.scanning": "Scanning",
    "nh.ports.scanningPorts": "Scanning {n} ports...",
    "nh.ports.portsScanned": "{n} ports scanned",
    "nh.ports.openCount": "{n} open",
    "nh.ports.statusOpen": "open",
    "nh.ports.statusClosed": "closed",
    "nh.ports.statusFiltered": "filtered",
    "nh.ports.statusScanning": "scanning",
    "nh.ports.checkSpecific": "Check Specific Port",
    "nh.ports.hostPlaceholder": "host or IP",
    "nh.ports.portPlaceholder": "Port",
    "nh.ports.goBtn": "Go",
    "nh.ports.portResult": "Port {port} — {status}",
    "nh.ports.note": "Browser-based scan via HTTP probing. Firewalls and CORS may affect accuracy.",
    "nh.ports.historyLabel": "{host} — {open} open port{plural} ({ports})",
    "nh.ports.none": "none",

    "nh.headers.title": "HTTP Headers Checker",
    "nh.headers.placeholder": "https://example.com",
    "nh.headers.error": "Could not fetch headers. The site may be blocking external requests.",
    "nh.headers.securityHeadersFor": "Security Headers — {domain}",
    "nh.headers.present": "present",
    "nh.headers.allHeaders": "All Response Headers",
    "nh.headers.historyLabel": "{url} — Security {score}/6 · HTTP {status}",

    "nh.traceroute.title": "Traceroute",
    "nh.traceroute.placeholder": "google.com",
    "nh.traceroute.tracing": "Tracing...",
    "nh.traceroute.traceBtn": "🗺 Trace",
    "nh.traceroute.note": "DNS hop analysis — approximates the resolution path to the target host.",
    "nh.traceroute.hopAnalysisFor": "Hop Analysis — {domain}",
    "nh.traceroute.complete": "✓ Complete",
    "nh.traceroute.timeout": "TIMEOUT",
    "nh.traceroute.moreRecords": "+{n} more",
    "nh.traceroute.localDns": "Local DNS Resolver",
    "nh.traceroute.rootDns": "Root DNS Servers",
    "nh.traceroute.tldNameservers": "TLD Nameservers (.{tld})",
    "nh.traceroute.authoritativeNs": "Authoritative NS ({domain})",
    "nh.traceroute.aRecordResolution": "A Record Resolution",
    "nh.traceroute.finalHost": "Final Host ({domain})",
    "nh.traceroute.historyLabel": "{domain} — {hops} hops",

    "sc.toolCount": "25 tools",
    "sc.searchPlaceholder": "Search tools… (press \"/\" to focus)",
    "sc.noResults": "No results for \"{query}\"",
    "sc.cats.all": "All",
    "sc.cats.favorites": "Favorites",
    "sc.cats.recent": "Recent",
    "sc.cats.finance": "Finance",
    "sc.cats.health": "Health",
    "sc.cats.dev": "Dev Tools",
    "sc.cats.text": "Text",
    "sc.cats.gen": "Generators",
    "sc.cats.convert": "Converters",
    "sc.seo.whatIsIt": "What is it?",
    "sc.seo.howItWorks": "How it works",
    "sc.seo.formula": "Formula",
    "sc.seo.examples": "Examples",
    "sc.seo.inputLabel": "Input:",
    "sc.seo.faqTitle": "Frequently Asked Questions",

    "sc.shared.copy": "Copy",
    "sc.shared.copied": "✓ Copied",
    "sc.shared.copyAriaCopied": "Copied to clipboard",
    "sc.shared.copyAria": "Copy to clipboard",

    "sc.share.usedTool": "I just used the {name} on SmartCalc Hub — free & instant! 🧮",
    "sc.share.titlePrefix": "SmartCalc — {name}",
    "sc.scenario.comparisonTitle": "Scenario Comparison — {name}",
  },
  fr: {
    "home.headline": "Tout Ce Qu'il Vous Faut.",
    "home.headlineSub": "Une Boîte à Outils Puissante.",
    "home.description": "Outils en ligne gratuits. Sans inscription.",
    "nav.pdfTools": "Outils PDF",
    "nav.imageTools": "Outils Image",
    "nav.calculators": "Calculatrices",
    "nav.converters": "Convertisseurs",
    "nav.network": "Réseau",
    "nav.allTools": "Tous les outils",
    "nav.searchTools": "Rechercher des outils",
    "nav.commandPalette": "Palette de commandes (Ctrl+K)",
    "nav.switchToLight": "Passer en mode clair",
    "nav.switchToDark": "Passer en mode sombre",
    "nav.openMenu": "Ouvrir le menu",
    "nav.closeMenu": "Fermer le menu",
    "nav.search": "Rechercher",
    "nav.lightMode": "Mode clair",
    "nav.darkMode": "Mode sombre",
    "nav.language": "Langue",

    "search.placeholder": "Rechercher outils, convertisseurs, calculatrices...",
    "search.clear": "Effacer la recherche",
    "search.noResults": "Aucun résultat pour",
    "search.results": "Résultats de recherche",

    "palette.placeholder": "Rechercher outils, convertisseurs, calculatrices...",
    "palette.recentAndActions": "Récents et actions rapides",
    "palette.results": "résultats",
    "palette.noToolsFound": "Aucun outil trouvé pour",
    "palette.tryDifferentKeyword": "Essayez un autre mot-clé",
    "palette.quickAction": "Action rapide",
    "palette.favorite": "favori",
    "palette.recentlyUsed": "utilisé récemment",
    "palette.usedTimes": "utilisé {n} fois",
    "palette.fav": "Favori",
    "palette.recent": "Récent",
    "palette.removeFromFavorites": "Retirer {name} des favoris",
    "palette.addToFavorites": "Ajouter {name} aux favoris",
    "palette.navigate": "naviguer",
    "palette.open": "ouvrir",
    "palette.close": "fermer",
    "palette.showTrending": "Afficher les outils tendance",
    "palette.showNewest": "Afficher les outils récents",
    "palette.showPopular": "Afficher les outils populaires",
    "palette.openPdfTools": "Ouvrir les outils PDF",
    "palette.openImageTools": "Ouvrir les outils Image",
    "palette.openCalculators": "Ouvrir les calculatrices",
    "palette.openNetworkTools": "Ouvrir les outils réseau",
    "palette.openAiWriting": "Ouvrir l'assistant IA",

    "toolCard.openTool": "Ouvrir l'outil →",
    "toolCard.nextStep": "Étape suivante →",
    "toolCard.toolsCount": "outils →",
    "toolCard.trending": "Tendance",
    "toolCard.removeFromFavorites": "Retirer des favoris",
    "toolCard.addToFavorites": "Ajouter aux favoris",

    "footer.tagline": "Des outils en ligne gratuits pour tous. Sans inscription, sans limites, sans logiciel.",
    "footer.toolsHeading": "Outils",
    "footer.resourcesHeading": "Ressources",
    "footer.companyHeading": "Entreprise",
    "footer.pdfTools": "Outils PDF",
    "footer.imageTools": "Outils Image",
    "footer.calculators": "Calculatrices",
    "footer.converters": "Convertisseurs",
    "footer.blog": "Blog",
    "footer.tutorials": "Tutoriels",
    "footer.apiDocs": "Documentation API",
    "footer.changelog": "Journal des modifications",
    "footer.about": "À propos",
    "footer.privacyPolicy": "Politique de confidentialité",
    "footer.termsOfUse": "Conditions d'utilisation",
    "footer.contact": "Contact",
    "footer.copyright": "© 2026 CHRONOS. Tous droits réservés.",
    "footer.madeWith": "Fait avec ❤️ pour le web",

    "nh.ip.title": "Votre Adresse IP",
    "nh.ip.detecting": "Détection en cours...",
    "nh.ip.copy": "Copier l'IP",
    "nh.ip.copied": "✓ Copié !",
    "nh.ip.error": "Impossible de récupérer votre adresse IP. Vous êtes peut-être derrière un VPN ou un pare-feu.",
    "nh.ip.connectionDetails": "Détails de Connexion",
    "nh.ip.isp": "FAI / Opérateur",
    "nh.ip.timezone": "Fuseau Horaire",
    "nh.ip.latitude": "Latitude",
    "nh.ip.longitude": "Longitude",
    "nh.ip.region": "Région",
    "nh.ip.country": "Pays",
    "nh.ip.refresh": "↻ Actualiser",
    "nh.history.title": "Historique ({n})",
    "nh.history.exportCsv": "↓ Exporter CSV",
    "nh.history.clear": "Effacer",

    "nh.whois.title": "Recherche Whois",
    "nh.whois.placeholder": "github.com",
    "nh.whois.error": "La recherche Whois a échoué. Essayez un domaine enregistré (ex. google.com).",
    "nh.whois.registrar": "Registraire",
    "nh.whois.dnssec": "DNSSEC",
    "nh.whois.created": "Créé",
    "nh.whois.updated": "Mis à jour",
    "nh.whois.expires": "Expire",
    "nh.whois.status": "Statut",
    "nh.whois.nameservers": "Serveurs de Noms",
    "nh.whois.signed": "Signé ✓",
    "nh.whois.unsigned": "Non Signé",

    "nh.ssl.title": "Vérificateur de Certificat SSL",
    "nh.ssl.placeholder": "example.com",
    "nh.ssl.error": "La vérification SSL a échoué",
    "nh.ssl.noCerts": "Aucun certificat trouvé",
    "nh.ssl.daysRemaining": "jours restants",
    "nh.ssl.issuer": "Émetteur",
    "nh.ssl.subject": "Sujet",
    "nh.ssl.validFrom": "Valide Depuis",
    "nh.ssl.expires": "Expire",
    "nh.ssl.totalCerts": "Total Certificats (CT)",
    "nh.ssl.statusValid": "VALIDE",
    "nh.ssl.statusExpiringSoon": "EXPIRE BIENTÔT",
    "nh.ssl.statusExpired": "EXPIRÉ",
    "nh.ssl.statusInvalid": "INVALIDE",
    "nh.ssl.historyValid": "✓ Valide",
    "nh.ssl.historyInvalid": "✗ Invalide",

    "nh.domainAge.title": "Vérificateur d'Âge de Domaine",
    "nh.domainAge.placeholder": "wikipedia.org",
    "nh.domainAge.errorNoDate": "Date de création introuvable pour ce domaine.",
    "nh.domainAge.error": "Impossible de récupérer les données d'enregistrement du domaine.",
    "nh.domainAge.years": "Années",
    "nh.domainAge.months": "Mois",
    "nh.domainAge.days": "Jours",
    "nh.domainAge.trustScore": "Score de Confiance",
    "nh.domainAge.registered": "Enregistré",
    "nh.domainAge.expires": "Expire",
    "nh.domainAge.lastUpdated": "Dernière Mise à Jour",
    "nh.domainAge.totalDays": "Total Jours",
    "nh.domainAge.trustHigh": "Très Fiable",
    "nh.domainAge.trustEstablished": "Établi",
    "nh.domainAge.trustModerate": "Modéré",
    "nh.domainAge.trustNew": "Nouveau Domaine",

    "nh.speed.title": "Vitesse de Connexion Internet",
    "nh.speed.download": "Téléchargement",
    "nh.speed.ping": "Ping",
    "nh.speed.runningTest": "Test en cours...",
    "nh.speed.running": "En cours...",
    "nh.speed.runAgain": "↻ Relancer",
    "nh.speed.startTest": "▶ Démarrer le Test",
    "nh.speed.noteTitle": "Note :",
    "nh.speed.noteBody": "Ceci est un Estimateur de Débit — il télécharge un fichier test directement depuis les serveurs edge de Cloudflare et mesure le débit dans votre navigateur. Les résultats reflètent la performance réelle de votre connexion.",
    "nh.speed.logMeasuringLatency": "📡 Mesure de la latence (3 échantillons)...",
    "nh.speed.logPingResult": "✓ Ping : {ms}ms (meilleur sur 3)",
    "nh.speed.logPingUnavailable": "⚠ Ping indisponible, utilisation d'une estimation",
    "nh.speed.logMeasuringDownload": "⬇ Mesure de la vitesse de téléchargement...",
    "nh.speed.logDownloadResult": "✓ Téléchargement : {mbps} Mbps",
    "nh.speed.logDownloadFailed": "✗ Le test de téléchargement a échoué — vérifiez votre connexion",
    "nh.speed.logImageFallback": "⟳ Utilisation du minutage image de secours...",
    "nh.speed.ratingExcellent": "EXCELLENT",
    "nh.speed.ratingGood": "BON",
    "nh.speed.ratingAverage": "MOYEN",
    "nh.speed.ratingSlow": "LENT",
    "nh.speed.historyLabel": "↓ {download} Mbps · Ping {ping}ms · {rating}",

    "nh.status.title": "Vérificateur d'État de Site",
    "nh.status.placeholder": "example.com ou https://example.com",
    "nh.status.checkButton": "Vérifier",
    "nh.status.popularSites": "Services Populaires",
    "nh.status.checkAny": "Vérifier N'importe Quel Site",
    "nh.status.checkAll": "↻ Tout Vérifier",
    "nh.status.prodNote": "Note : en production, les vérifications passent par une route serverless Vercel dédiée /api/check-site pour plus de précision. L'aperçu utilise corsproxy.io.",
    "nh.status.checking": "● Vérification...",
    "nh.status.online": "● EN LIGNE",
    "nh.status.down": "● EN PANNE",
    "nh.status.idle": "○ Inactif",
    "nh.status.responseTime": "Temps de Réponse",
    "nh.status.httpStatus": "Statut HTTP",
    "nh.status.historyUp": "✓ En ligne",
    "nh.status.historyDown": "✗ En panne",

    "nh.password.title": "Générateur de Mot de Passe",
    "nh.password.copy": "Copier",
    "nh.password.copied": "✓ Copié !",
    "nh.password.length": "Longueur",
    "nh.password.uppercase": "Majuscules (A-Z)",
    "nh.password.lowercase": "Minuscules (a-z)",
    "nh.password.numbers": "Chiffres (0-9)",
    "nh.password.symbols": "Symboles (!@#$...)",
    "nh.password.strengthWeak": "Faible",
    "nh.password.strengthFair": "Moyen",
    "nh.password.strengthStrong": "Fort",
    "nh.password.strengthVeryStrong": "Très Fort",
    "nh.password.generate": "↻ Générer Nouveau",
    "nh.password.entropy": "Entropie : {bits} bits",
    "nh.password.generatedTitle": "Mot de Passe Généré",
    "nh.password.generateAria": "Générer un nouveau mot de passe",
    "nh.password.passwordLength": "Longueur du Mot de Passe",
    "nh.password.characterTypes": "Types de Caractères",
    "nh.password.generateNewBtn": "↻ Générer un Nouveau Mot de Passe",
    "nh.password.recentPasswords": "Mots de Passe Récents",

    "nh.dns.title": "Recherche DNS",
    "nh.dns.placeholder": "example.com",
    "nh.dns.error": "La recherche DNS a échoué",
    "nh.dns.recordsFor": "Enregistrements {type} — {domain}",
    "nh.dns.noRecords": "Aucun enregistrement trouvé pour ce type.",
    "nh.dns.answer": "Réponse",
    "nh.dns.authority": "Autorité",
    "nh.dns.ttl": "TTL",
    "nh.dns.domainLabel": "Domaine",
    "nh.dns.recordType": "Type d'Enregistrement",
    "nh.dns.lookingUp": "Recherche...",
    "nh.dns.lookupBtn": "🔍 Rechercher",
    "nh.dns.nxdomain": "Domaine introuvable (NXDOMAIN)",
    "nh.dns.errorCode": "Code d'erreur DNS {code}",
    "nh.dns.authorityRecords": "ENREGISTREMENTS D'AUTORITÉ",
    "nh.dns.historyLabel": "{domain} [{type}] — {count} enregistrement{plural}",

    "nh.ping.pingPopular": "Pinguer les Serveurs Populaires",
    "nh.ping.pingAll": "▶ Tout Pinguer",
    "nh.ping.notTested": "○ Non testé",
    "nh.ping.pinging": "● Ping en cours...",
    "nh.ping.unreachable": "✕ Inaccessible",
    "nh.ping.qualityExcellent": "Excellent",
    "nh.ping.qualityGood": "Bon",
    "nh.ping.qualityFair": "Moyen",
    "nh.ping.qualityPoor": "Mauvais",
    "nh.ping.minMax": "min {min} / max {max}",
    "nh.ping.pingCustomHost": "Pinguer un Hôte Personnalisé",
    "nh.ping.placeholder": "example.com",
    "nh.ping.pingBtn": "Ping",
    "nh.ping.hostUnreachable": "✕ Hôte inaccessible ou bloqué",
    "nh.ping.avg": "MOY",
    "nh.ping.min": "MIN",
    "nh.ping.max": "MAX",
    "nh.ping.note": "Le ping navigateur utilise le minutage HTTP (pas ICMP) — 5 échantillons, rapporte min/moy/max.",
    "nh.ping.historyLabel": "{host} — moy {avg}ms · min {min} / max {max}",

    "nh.ports.title": "Scanneur de Ports",
    "nh.ports.placeholder": "example.com ou IP",
    "nh.ports.scanBtn": "🔌 Scanner",
    "nh.ports.scanning": "Scan en cours",
    "nh.ports.scanningPorts": "Scan de {n} ports...",
    "nh.ports.portsScanned": "{n} ports scannés",
    "nh.ports.openCount": "{n} ouverts",
    "nh.ports.statusOpen": "ouvert",
    "nh.ports.statusClosed": "fermé",
    "nh.ports.statusFiltered": "filtré",
    "nh.ports.statusScanning": "scan en cours",
    "nh.ports.checkSpecific": "Vérifier un Port Spécifique",
    "nh.ports.hostPlaceholder": "hôte ou IP",
    "nh.ports.portPlaceholder": "Port",
    "nh.ports.goBtn": "Go",
    "nh.ports.portResult": "Port {port} — {status}",
    "nh.ports.note": "Scan basé navigateur via sondage HTTP. Les pare-feux et CORS peuvent affecter la précision.",
    "nh.ports.historyLabel": "{host} — {open} port{plural} ouvert{plural} ({ports})",
    "nh.ports.none": "aucun",

    "nh.headers.title": "Vérificateur d'En-têtes HTTP",
    "nh.headers.placeholder": "https://example.com",
    "nh.headers.error": "Impossible de récupérer les en-têtes. Le site bloque peut-être les requêtes externes.",
    "nh.headers.securityHeadersFor": "En-têtes de Sécurité — {domain}",
    "nh.headers.present": "présents",
    "nh.headers.allHeaders": "Tous les En-têtes de Réponse",
    "nh.headers.historyLabel": "{url} — Sécurité {score}/6 · HTTP {status}",

    "nh.traceroute.title": "Traceroute",
    "nh.traceroute.placeholder": "google.com",
    "nh.traceroute.tracing": "Traçage...",
    "nh.traceroute.traceBtn": "🗺 Tracer",
    "nh.traceroute.note": "Analyse de saut DNS — approxime le chemin de résolution vers l'hôte cible.",
    "nh.traceroute.hopAnalysisFor": "Analyse des Sauts — {domain}",
    "nh.traceroute.complete": "✓ Terminé",
    "nh.traceroute.timeout": "EXPIRÉ",
    "nh.traceroute.moreRecords": "+{n} de plus",
    "nh.traceroute.localDns": "Résolveur DNS Local",
    "nh.traceroute.rootDns": "Serveurs DNS Racine",
    "nh.traceroute.tldNameservers": "Serveurs de Noms TLD (.{tld})",
    "nh.traceroute.authoritativeNs": "NS Autoritaire ({domain})",
    "nh.traceroute.aRecordResolution": "Résolution d'Enregistrement A",
    "nh.traceroute.finalHost": "Hôte Final ({domain})",
    "nh.traceroute.historyLabel": "{domain} — {hops} sauts",

    "sc.toolCount": "25 outils",
    "sc.searchPlaceholder": "Rechercher des outils… (appuyez sur \"/\" pour focus)",
    "sc.noResults": "Aucun résultat pour « {query} »",
    "sc.cats.all": "Tous",
    "sc.cats.favorites": "Favoris",
    "sc.cats.recent": "Récents",
    "sc.cats.finance": "Finance",
    "sc.cats.health": "Santé",
    "sc.cats.dev": "Dev",
    "sc.cats.text": "Texte",
    "sc.cats.gen": "Générateurs",
    "sc.cats.convert": "Convertisseurs",
    "sc.seo.whatIsIt": "Qu'est-ce que c'est ?",
    "sc.seo.howItWorks": "Comment ça marche",
    "sc.seo.formula": "Formule",
    "sc.seo.examples": "Exemples",
    "sc.seo.inputLabel": "Entrée :",
    "sc.seo.faqTitle": "Questions Fréquentes",

    "sc.shared.copy": "Copier",
    "sc.shared.copied": "✓ Copié",
    "sc.shared.copyAriaCopied": "Copié dans le presse-papiers",
    "sc.shared.copyAria": "Copier dans le presse-papiers",

    "sc.share.usedTool": "Je viens d'utiliser {name} sur SmartCalc Hub — gratuit et instantané ! 🧮",
    "sc.share.titlePrefix": "SmartCalc — {name}",
    "sc.scenario.comparisonTitle": "Comparaison de Scénarios — {name}",

    // ── Tool search keywords (fr) — Batch 2: Finance
    "tool.mortgage.keywords": ["prêt", "emprunt", "maison", "hypothèque", "mensualité", "immobilier"],
    "tool.emi.keywords": ["prêt", "mensualité", "échéance", "banque", "remboursement"],
    "tool.vat.keywords": ["taxe", "tva", "valeur ajoutée", "taxe de vente"],
    "tool.discount.keywords": ["solde", "pourcentage de réduction", "promo", "réduction"],
    "tool.percentage.keywords": ["pourcentage", "ratio", "proportion"],
    "tool.tip.keywords": ["restaurant", "pourboire", "partage addition"],
    "tool.currency.keywords": ["devise", "taux de change", "mga", "ariary", "usd", "eur", "argent"],
    "tool.compound.keywords": ["épargne", "investissement", "taux d'intérêt", "valeur future", "croissance"],

    // ── Tool search keywords (fr) — Batch 3: Health + Dev
    "tool.bmi.keywords": ["masse corporelle", "poids", "taille", "imc", "obèse"],
    "tool.age.keywords": ["anniversaire", "né", "date de naissance", "années"],
    "tool.calories.keywords": ["besoins caloriques", "métabolisme", "régime", "nutrition", "kcal"],
    "tool.base64.keywords": ["encoder", "décoder", "utf8", "btoa", "atob"],
    "tool.password.keywords": ["aléatoire", "sécurisé", "générateur", "mot de passe fort"],
    "tool.uuid.keywords": ["guid", "identifiant unique", "v4", "id aléatoire"],
    "tool.sha256.keywords": ["hachage", "crypto", "somme de contrôle", "empreinte"],
    "tool.json.keywords": ["formater", "embellir", "minifier", "analyser", "impression soignée"],
    "tool.qr.keywords": ["qrcode", "scanner", "code-barres", "lien"],

    // ── Tool search keywords (fr) — Batch 4: Text + Converters (final)
    "tool.wordcount.keywords": ["caractères", "mots", "lettres", "compter texte"],
    "tool.textdiff.keywords": ["différence", "comparer", "comparaison", "changements"],
    "tool.lorem.keywords": ["texte de remplissage", "faux texte", "latin"],
    "tool.casegen.keywords": ["majuscule", "minuscule", "camelcase", "casse de titre", "snake case"],
    "tool.randompick.keywords": ["roue de la décision", "choix aléatoire", "tirage au sort", "sélecteur d'équipe", "gagnant"],
    "tool.temp.keywords": ["celsius", "fahrenheit", "kelvin", "degrés"],
    "tool.binary.keywords": ["décimal", "hexadécimal", "octal", "base numérique", "bits"],
    "tool.rgb.keywords": ["couleur", "code hexadécimal", "css", "couleur html"],
    "tool.timezone.keywords": ["utc", "gmt", "horloge mondiale", "décalage horaire"],
    "tool.units.keywords": ["longueur", "poids", "km", "miles", "kg", "lbs", "mètre", "volume", "surface", "vitesse", "pression"],
    "tool.roman.keywords": ["chiffres romains", "I V X L C D M", "antique"],
    "tool.datediff.keywords": ["jours jusqu'à", "échéance", "compte à rebours", "calculateur de dates", "jours entre"],
    // ── registryCategories (fr) — Phase A, Batch 1: all 7 categories
    "regCat.ai-tools.name": "Outils IA",
    "regCat.ai-tools.title": "Outils IA Gratuits en Ligne — Sans Inscription | CHRONOS",
    "regCat.ai-tools.description": "Outils IA puissants et gratuits en ligne : générateur d'images IA, assistant d'écriture IA, suppression d'arrière-plan IA, résumeur de texte, et plus. Sans compte.",
    "regCat.ai-tools.keywords": ["outils ia en ligne", "outils ia gratuits", "outils intelligence artificielle", "générateur image ia", "générateur texte ia", "outil écriture ia"],
    "regCat.pdf-tools.name": "Outils PDF",
    "regCat.pdf-tools.title": "Outils PDF Gratuits en Ligne — Fusionner, Diviser, Compresser | CHRONOS",
    "regCat.pdf-tools.description": "Outils PDF gratuits en ligne : fusionner, diviser, compresser, convertir PDF en Word, Excel, JPG et plus. Sans installation. Fonctionne sur tout appareil.",
    "regCat.pdf-tools.keywords": ["outils pdf en ligne", "éditeur pdf gratuit", "fusionner pdf en ligne", "diviser pdf", "compresser pdf", "convertisseur pdf", "pdf en word", "pdf en jpg"],
    "regCat.image-tools.name": "Outils Image",
    "regCat.image-tools.title": "Outils Image Gratuits en Ligne — Redimensionner, Compresser | CHRONOS",
    "regCat.image-tools.description": "Outils image gratuits en ligne : supprimer l'arrière-plan, compresser des images, redimensionner, recadrer, convertir PNG/JPG, ajouter des filigranes, et plus. Résultats instantanés.",
    "regCat.image-tools.keywords": ["outils image en ligne", "éditeur image gratuit", "supprimer arrière-plan en ligne", "compresser image", "redimensionner image en ligne", "convertisseur image"],
    "regCat.calculators.name": "Calculatrices",
    "regCat.calculators.title": "Calculatrices Gratuites en Ligne — IMC, Prêt, Âge et Plus | CHRONOS",
    "regCat.calculators.description": "Calculatrices gratuites en ligne pour un usage quotidien : calculateur d'IMC, de prêt, d'âge, de pourcentage, d'hypothèque, de moyenne et plus.",
    "regCat.calculators.keywords": ["calculatrice en ligne", "calculatrices gratuites", "calculateur imc", "calculateur de prêt", "calculateur d'âge", "calculateur de pourcentage", "calculateur d'hypothèque"],
    "regCat.converters.name": "Convertisseurs",
    "regCat.converters.title": "Convertisseurs d'Unités et de Fichiers Gratuits en Ligne | CHRONOS",
    "regCat.converters.description": "Convertisseurs d'unités gratuits en ligne : longueur, poids, température, surface, vitesse, devises, RGB en HEX, convertisseur de casse de texte et plus.",
    "regCat.converters.keywords": ["convertisseur d'unités en ligne", "convertisseur gratuit", "convertisseur de longueur", "convertisseur de devises", "convertisseur de température", "rgb en hex", "convertisseur de texte"],
    "regCat.internet-tools.name": "Outils Internet",
    "regCat.internet-tools.title": "Outils Internet et Réseau Gratuits en Ligne | CHRONOS",
    "regCat.internet-tools.description": "Outils internet gratuits en ligne : test de débit, recherche IP, recherche DNS, Whois, vérificateur de ping, vérificateur SSL, vérificateur d'état de site et plus.",
    "regCat.internet-tools.keywords": ["test de débit internet", "recherche ip", "recherche dns", "recherche whois", "test de ping en ligne", "vérificateur ssl", "vérificateur d'état de site"],
    "regCat.developer-tools.name": "Outils Développeur",
    "regCat.developer-tools.title": "Outils Développeur Gratuits en Ligne — JSON, Base64, Regex | CHRONOS",
    "regCat.developer-tools.description": "Outils développeur gratuits en ligne : formateur JSON, encodeur/décodeur Base64, encodeur URL, testeur Regex, formateur HTML, minifieur CSS et plus.",
    "regCat.developer-tools.keywords": ["outils développeur en ligne", "formateur json", "encodeur base64", "encodeur décodeur url", "testeur regex", "formateur html", "minifieur css", "minifieur javascript"],
    // ── registryTools (fr) — Phase B, Batch 1: ai-tools (6)
    "regTool.ai-text-summarizer.name": "Résumeur de Texte IA",
    "regTool.ai-text-summarizer.title": "Résumeur de Texte IA Gratuit en Ligne — Résumez Tout Texte Instantanément",
    "regTool.ai-text-summarizer.description": "Résumez de longs articles, essais ou documents en quelques secondes avec notre résumeur de texte IA gratuit. Collez n'importe quel texte et obtenez un résumé clair et concis instantanément.",
    "regTool.ai-text-summarizer.keywords": ["résumeur de texte ia", "résumeur de texte en ligne", "résumer un texte gratuit", "résumeur d'article", "résumeur automatique", "outil de résumé en ligne"],
    "regTool.ai-writing-assistant.name": "Assistant d'Écriture IA",
    "regTool.ai-writing-assistant.title": "Assistant d'Écriture IA Gratuit en Ligne — Écrivez Mieux, Plus Vite",
    "regTool.ai-writing-assistant.description": "Améliorez votre écriture avec notre assistant d'écriture IA gratuit. Corrigez la grammaire, réécrivez des phrases, développez des paragraphes et générez du contenu instantanément.",
    "regTool.ai-writing-assistant.keywords": ["assistant d'écriture ia", "écrivain ia en ligne", "outil d'écriture ia gratuit", "correcteur de grammaire ia", "réécriture de phrase", "générateur de contenu gratuit"],
    "regTool.ai-image-generator.name": "Générateur d'Images IA",
    "regTool.ai-image-generator.title": "Générateur d'Images IA Gratuit en Ligne — Créez des Images à partir de Texte",
    "regTool.ai-image-generator.description": "Générez des images époustouflantes à partir de descriptions textuelles avec notre générateur d'images IA gratuit. Créez des œuvres d'art, illustrations et photos grâce à l'intelligence artificielle.",
    "regTool.ai-image-generator.keywords": ["générateur d'images ia", "texte en image ia", "générateur d'images ia gratuit", "générateur d'art ia", "générer une image à partir de texte", "générateur de photos ia"],
    "regTool.ai-background-remover.name": "Suppresseur d'Arrière-Plan IA",
    "regTool.ai-background-remover.title": "Suppresseur d'Arrière-Plan IA Gratuit — Supprimez l'Arrière-Plan Instantanément",
    "regTool.ai-background-remover.description": "Supprimez l'arrière-plan d'une image en un clic grâce à l'IA. Gratuit, rapide et précis. Téléchargez votre photo et obtenez le PNG transparent instantanément.",
    "regTool.ai-background-remover.keywords": ["suppresseur d'arrière-plan ia", "supprimer arrière-plan ia", "effaceur d'arrière-plan en ligne", "créateur d'arrière-plan transparent", "supprimer le fond gratuit", "ia suppression d'arrière-plan"],
    "regTool.ai-grammar-checker.name": "Correcteur Grammatical IA",
    "regTool.ai-grammar-checker.title": "Correcteur Grammatical IA Gratuit en Ligne — Corrigez la Grammaire Instantanément",
    "regTool.ai-grammar-checker.description": "Vérifiez et corrigez les erreurs de grammaire, d'orthographe et de ponctuation instantanément avec notre correcteur grammatical IA gratuit. Rédigez du contenu sans faute à chaque fois.",
    "regTool.ai-grammar-checker.keywords": ["correcteur grammatical ia", "vérificateur de grammaire en ligne gratuit", "correcteur orthographique", "vérificateur de ponctuation", "outil de grammaire", "vérificateur d'erreurs d'écriture"],
    "regTool.ai-code-explainer.name": "Explicateur de Code IA",
    "regTool.ai-code-explainer.title": "Explicateur de Code IA Gratuit — Comprenez Tout Code Instantanément",
    "regTool.ai-code-explainer.description": "Collez n'importe quel code et obtenez une explication claire instantanément. Notre explicateur de code IA gratuit prend en charge Python, JavaScript, Java, C++ et plus.",
    "regTool.ai-code-explainer.keywords": ["explicateur de code ia", "expliquer du code en ligne", "outil d'explication de code", "comprendre le code ia", "code en explication", "explicateur de code gratuit"],
    // ── registryTools (fr) — Phase B, Batch 2: pdf-tools (8)
    "regTool.merge-pdf.name": "Fusionner PDF",
    "regTool.merge-pdf.title": "Fusionner des Fichiers PDF en Ligne Gratuit — Combiner des PDF en Quelques Secondes",
    "regTool.merge-pdf.description": "Fusionnez plusieurs fichiers PDF en un seul en ligne gratuitement. Glissez, déposez, réorganisez et combinez vos PDF instantanément. Sans logiciel, sans compte.",
    "regTool.merge-pdf.keywords": ["fusionner pdf", "combiner pdf en ligne", "joindre fichiers pdf", "fusionner pdf gratuit", "combiner plusieurs pdf", "fusionneur pdf en ligne", "fusionner pdf en ligne gratuit"],
    "regTool.split-pdf.name": "Diviser PDF",
    "regTool.split-pdf.title": "Diviser un PDF en Ligne Gratuit — Extraire des Pages de PDF Instantanément",
    "regTool.split-pdf.description": "Divisez un PDF en pages individuelles ou extrayez des pages spécifiques en ligne gratuitement. Choisissez des plages de pages ou divisez chaque page. Sans compte requis.",
    "regTool.split-pdf.keywords": ["diviser pdf en ligne", "diviser pdf gratuit", "extraire pages d'un pdf", "diviseur pdf", "séparer pages pdf", "découper pdf", "extracteur de pages pdf"],
    "regTool.compress-pdf.name": "Compresser PDF",
    "regTool.compress-pdf.title": "Compresser un PDF en Ligne Gratuit — Réduire la Taille d'un PDF Instantanément",
    "regTool.compress-pdf.description": "Compressez la taille de vos fichiers PDF en ligne gratuitement sans perte de qualité. Réduisez les PDF volumineux pour l'envoi par e-mail, le téléchargement ou le stockage. Instantané, sécurisé, sans inscription.",
    "regTool.compress-pdf.keywords": ["compresser pdf en ligne", "réduire taille pdf", "compresseur pdf gratuit", "réduire pdf", "compresser pdf sans perte de qualité", "rendre pdf plus petit", "réducteur de taille pdf"],
    "regTool.pdf-to-word.name": "PDF en Word",
    "regTool.pdf-to-word.title": "Convertisseur PDF en Word en Ligne Gratuit — Convertir PDF en DOCX",
    "regTool.pdf-to-word.description": "Convertissez un PDF en document Word modifiable (DOCX) en ligne gratuitement. Préservez la mise en forme, les polices et la mise en page. Rapide, précis, sans inscription.",
    "regTool.pdf-to-word.keywords": ["pdf en word", "pdf en docx en ligne", "convertir pdf en word gratuit", "convertisseur pdf en word", "pdf en word modifiable", "extraire texte d'un pdf"],
    "regTool.pdf-to-excel.name": "PDF en Excel",
    "regTool.pdf-to-excel.title": "Convertisseur PDF en Excel en Ligne Gratuit — Convertir des Tableaux PDF en XLSX",
    "regTool.pdf-to-excel.description": "Convertissez des fichiers PDF contenant des tableaux en feuilles de calcul Excel modifiables (XLSX) en ligne gratuitement. Extrayez les données avec précision. Sans logiciel requis.",
    "regTool.pdf-to-excel.keywords": ["pdf en excel", "pdf en xlsx en ligne", "convertir pdf en excel gratuit", "extracteur de tableau pdf", "pdf en feuille de calcul", "extraire tableau d'un pdf"],
    "regTool.pdf-to-jpg.name": "PDF en JPG",
    "regTool.pdf-to-jpg.title": "Convertisseur PDF en JPG en Ligne Gratuit — Convertir des Pages PDF en Images",
    "regTool.pdf-to-jpg.description": "Convertissez des pages PDF en images JPG de haute qualité en ligne gratuitement. Extrayez chaque page sous forme d'image ou choisissez des pages spécifiques. Rapide et sécurisé.",
    "regTool.pdf-to-jpg.keywords": ["pdf en jpg", "pdf en image en ligne", "convertir pdf en jpg gratuit", "page pdf en image", "pdf en png", "extraire images d'un pdf"],
    "regTool.jpg-to-pdf.name": "JPG en PDF",
    "regTool.jpg-to-pdf.title": "Convertisseur JPG en PDF en Ligne Gratuit — Convertir des Images en PDF",
    "regTool.jpg-to-pdf.description": "Convertissez JPG, PNG et d'autres formats d'image en PDF en ligne gratuitement. Combinez plusieurs images en un seul PDF. Sans filigrane, sans inscription.",
    "regTool.jpg-to-pdf.keywords": ["jpg en pdf", "image en pdf en ligne", "convertir jpg en pdf gratuit", "png en pdf", "photos en pdf", "plusieurs images en pdf", "convertisseur jpg pdf"],
    "regTool.rotate-pdf.name": "Pivoter PDF",
    "regTool.rotate-pdf.title": "Pivoter un PDF en Ligne Gratuit — Faire Pivoter des Pages PDF Instantanément",
    "regTool.rotate-pdf.description": "Faites pivoter les pages d'un PDF en ligne gratuitement. Pivotez des pages individuelles ou toutes les pages de 90°, 180° ou 270°. Sauvegardez la rotation de façon permanente. Sans inscription.",
    "regTool.rotate-pdf.keywords": ["pivoter pdf en ligne", "tourner pages pdf", "retourner page pdf", "tourner pdf", "pivoter pdf gratuit", "corriger orientation pdf", "outil de rotation pdf"],
    // ── registryTools (fr) — Phase B, Batch 3: image-tools (8 of 10)
    "regTool.remove-background.name": "Supprimer l'Arrière-Plan",
    "regTool.remove-background.title": "Supprimer l'Arrière-Plan d'une Image en Ligne Gratuit — Suppression Instantanée",
    "regTool.remove-background.description": "Supprimez l'arrière-plan de n'importe quelle image instantanément et gratuitement. Idéal pour les photos de produits, portraits et photos de profil. Téléchargez en PNG transparent.",
    "regTool.remove-background.keywords": ["supprimer arrière-plan en ligne", "supprimer fond d'image gratuit", "suppresseur d'arrière-plan", "fond transparent", "supprimer bg en ligne", "effaceur d'arrière-plan", "détourer image"],
    "regTool.image-compressor.name": "Compresseur d'Image",
    "regTool.image-compressor.title": "Compresser une Image en Ligne Gratuit — Réduire la Taille sans Perte de Qualité",
    "regTool.image-compressor.description": "Compressez vos images en ligne gratuitement. Réduisez la taille des fichiers JPG, PNG et WebP jusqu'à 90 % sans perte de qualité visible. Rapide, sécurisé, sans inscription.",
    "regTool.image-compressor.keywords": ["compresser image en ligne", "compresseur d'image gratuit", "réduire taille d'image", "compresser jpg en ligne", "compresser png gratuit", "réducteur de taille d'image", "optimiser image en ligne"],
    "regTool.resize-image.name": "Redimensionner Image",
    "regTool.resize-image.title": "Redimensionner une Image en Ligne Gratuit — Changer les Dimensions Instantanément",
    "regTool.resize-image.description": "Redimensionnez vos images en ligne gratuitement. Modifiez la largeur, la hauteur ou le pourcentage. Conservez le ratio d'aspect automatiquement. Compatible JPG, PNG, WebP et GIF.",
    "regTool.resize-image.keywords": ["redimensionner image en ligne", "redimensionneur d'image gratuit", "changer taille d'image", "agrandir image en ligne", "redimensionner photo", "changer dimensions d'image", "redimensionner jpg en ligne"],
    "regTool.crop-image.name": "Recadrer Image",
    "regTool.crop-image.title": "Recadrer une Image en Ligne Gratuit — Découper des Images Instantanément",
    "regTool.crop-image.description": "Recadrez vos images en ligne gratuitement. Découpez vos photos selon une taille personnalisée, un ratio d'aspect ou des dimensions en pixels précises. Compatible JPG, PNG, WebP. Sans inscription.",
    "regTool.crop-image.keywords": ["recadrer image en ligne", "recadreur d'image gratuit", "découper image en ligne", "rogner photo en ligne", "recadrer jpg gratuit", "recadrer photo selon la taille", "outil de recadrage personnalisé"],
    "regTool.png-to-jpg.name": "PNG en JPG",
    "regTool.png-to-jpg.title": "Convertisseur PNG en JPG en Ligne Gratuit — Convertir PNG en JPEG Instantanément",
    "regTool.png-to-jpg.description": "Convertissez vos images PNG en JPG en ligne gratuitement. Ajustez les paramètres de qualité et téléchargez des JPEG compressés instantanément. Sans inscription, sans filigrane.",
    "regTool.png-to-jpg.keywords": ["png en jpg", "convertir png en jpg en ligne", "png en jpeg gratuit", "convertisseur png", "changer png en jpg", "png en jpg en ligne gratuit"],
    "regTool.jpg-to-png.name": "JPG en PNG",
    "regTool.jpg-to-png.title": "Convertisseur JPG en PNG en Ligne Gratuit — Convertir JPEG en PNG Instantanément",
    "regTool.jpg-to-png.description": "Convertissez vos images JPG/JPEG au format PNG en ligne gratuitement. Conversion sans perte avec prise en charge de l'arrière-plan transparent. Rapide et gratuit.",
    "regTool.jpg-to-png.keywords": ["jpg en png", "convertir jpg en png en ligne", "jpeg en png gratuit", "convertisseur jpg", "changer jpg en png", "jpg en png transparent"],
    "regTool.watermark-tool.name": "Ajouter un Filigrane",
    "regTool.watermark-tool.title": "Ajouter un Filigrane à une Image en Ligne Gratuit — Texte et Logo",
    "regTool.watermark-tool.description": "Ajoutez des filigranes de texte ou de logo à vos images en ligne gratuitement. Personnalisez la position, l'opacité, la police et la couleur. Protégez vos photos instantanément.",
    "regTool.watermark-tool.keywords": ["ajouter filigrane en ligne", "filigraner image gratuit", "filigrane de texte", "filigrane de logo", "outil de filigrane d'image", "protéger image avec filigrane"],
    "regTool.blur-background.name": "Flouter l'Arrière-Plan",
    "regTool.blur-background.title": "Flouter l'Arrière-Plan d'une Image en Ligne Gratuit — Effet Mode Portrait",
    "regTool.blur-background.description": "Floutez l'arrière-plan de n'importe quelle photo en ligne gratuitement. Créez un magnifique effet bokeh/mode portrait. Téléchargez et récupérez instantanément. Aucune application nécessaire.",
    "regTool.blur-background.keywords": ["flouter arrière-plan en ligne", "flouter fond d'image gratuit", "effet mode portrait", "effet bokeh en ligne", "outil de flou d'arrière-plan", "flouter fond de photo"],
    // ── registryTools (fr) — Phase B, Batch 4: image-tools (2 final) + calculators (6 of 10)
    "regTool.color-picker.name": "Pipette à Couleur",
    "regTool.color-picker.title": "Pipette à Couleur en Ligne Gratuit — Prélevez des Couleurs d'Images et Plus",
    "regTool.color-picker.description": "Outil de pipette à couleur gratuit en ligne. Prélevez des couleurs sur des images, saisissez des valeurs HEX, RGB ou HSL, et obtenez des palettes de couleurs. Informations de couleur instantanées.",
    "regTool.color-picker.keywords": ["pipette à couleur en ligne", "prélever couleur d'image", "pipette couleur hex", "pipette couleur rgb", "outil pipette en ligne", "pipette à couleur gratuit", "trouver code couleur"],
    "regTool.image-flipper.name": "Retourner Image",
    "regTool.image-flipper.title": "Retourner une Image en Ligne Gratuit — Miroir Horizontal ou Vertical",
    "regTool.image-flipper.description": "Retournez ou mettez en miroir vos images en ligne gratuitement. Retournez horizontalement, verticalement, ou les deux. Compatible JPG, PNG, WebP. Téléchargez l'image retournée instantanément.",
    "regTool.image-flipper.keywords": ["retourner image en ligne", "miroir image gratuit", "retourner photo horizontal", "retourner photo vertical", "retourneur d'image", "retourner jpg en ligne"],
    "regTool.scientific-calculator.name": "Calculatrice Scientifique",
    "regTool.scientific-calculator.title": "Calculatrice Scientifique Gratuite en Ligne — Calculs Mathématiques Avancés",
    "regTool.scientific-calculator.description": "Calculatrice scientifique gratuite en ligne avec fonctions trigonométriques, logarithmes, exposants, fractions et plus. Support complet du clavier.",
    "regTool.scientific-calculator.keywords": ["calculatrice scientifique en ligne", "calculatrice avancée gratuite", "calculatrice mathématique", "calculatrice trigonométrique", "calc scientifique", "calculatrice scientifique en ligne gratuite"],
    "regTool.smart-calculator.name": "Calculatrice Intelligente",
    "regTool.smart-calculator.title": "Calculatrice Intelligente — 25 Calculatrices Gratuites en Ligne dans une Seule App",
    "regTool.smart-calculator.description": "Suite de calculatrices tout-en-un avec 25 outils : hypothèque, EMI, IMC, intérêts composés, devises, convertisseur d'unités, générateur de mot de passe et plus. Sans inscription.",
    "regTool.smart-calculator.keywords": ["calculatrice intelligente", "calculatrice tout-en-un", "suite de calculatrices en ligne", "calculateur d'hypothèque", "calculateur d'imc", "calculateur d'intérêts composés", "convertisseur d'unités", "convertisseur de devises"],
    "regTool.bmi-calculator.name": "Calculateur d'IMC",
    "regTool.bmi-calculator.title": "Calculateur d'IMC Gratuit en Ligne — Indice de Masse Corporelle",
    "regTool.bmi-calculator.description": "Calculez votre IMC (Indice de Masse Corporelle) instantanément et gratuitement. Compatible avec les unités métriques et impériales. Découvrez si vous êtes en sous-poids, normal, en surpoids ou obèse.",
    "regTool.bmi-calculator.keywords": ["calculateur d'imc", "calculateur indice de masse corporelle", "calculateur imc en ligne gratuit", "calculateur imc kg", "calculateur imc livres", "calculateur poids taille"],
    "regTool.age-calculator.name": "Calculateur d'Âge",
    "regTool.age-calculator.title": "Calculateur d'Âge Gratuit en Ligne — Calculez Votre Âge Exact",
    "regTool.age-calculator.description": "Calculez votre âge exact en années, mois, jours, heures et minutes. Découvrez combien de jours il reste avant votre prochain anniversaire. Calculateur d'âge en ligne gratuit.",
    "regTool.age-calculator.keywords": ["calculateur d'âge", "calculer âge en ligne", "calculateur d'âge gratuit", "quel âge ai-je", "calculateur d'anniversaire", "calculateur d'âge exact", "calculateur âge en jours"],
    "regTool.percentage-calculator.name": "Calculateur de Pourcentage",
    "regTool.percentage-calculator.title": "Calculateur de Pourcentage Gratuit en Ligne — Calculez les Pourcentages Instantanément",
    "regTool.percentage-calculator.description": "Calculez des pourcentages, des augmentations/diminutions en pourcentage, des différences de pourcentage et plus. Calculateur de pourcentage gratuit en ligne avec solutions détaillées.",
    "regTool.percentage-calculator.keywords": ["calculateur de pourcentage", "calculer pourcentage en ligne", "calculateur de pourcent gratuit", "calculateur d'augmentation en pourcentage", "différence de pourcentage", "pourcentage d'un nombre"],
    "regTool.loan-calculator.name": "Calculateur de Prêt",
    "regTool.loan-calculator.title": "Calculateur de Prêt Gratuit en Ligne — Paiement Mensuel et Calcul d'Intérêts",
    "regTool.loan-calculator.description": "Calculez les paiements mensuels de prêt, les intérêts totaux et le tableau d'amortissement pour tout prêt. Calculateur de prêt gratuit en ligne pour prêts personnels, automobiles et étudiants.",
    "regTool.loan-calculator.keywords": ["calculateur de prêt", "calculateur de paiement mensuel", "calculateur d'intérêt de prêt", "calculateur de prêt personnel", "calculateur de prêt auto", "calculateur d'amortissement de prêt", "calculateur de remboursement de prêt"],
  },
};

type DictShape = typeof DICT
type DictKey = keyof DictShape['en']

interface LangContextValue {
  lang: Lang
  setLang: (l: Lang) => void
  t: (key: string) => string
}

const LangContext = createContext<LangContextValue>({
  lang: 'en',
  setLang: () => {},
  t: (key: string) => key,
})

export function LangProvider({
  children,
  initialLang,
}: {
  children: React.ReactNode
  // Vainy avy amin'ny app/layout.tsx (server component), izay namaky
  // ilay cookie "ch-lang" alohan'ny SSR — izany no mahatonga ny
  // <html lang="..."> ho marina hatramin'ny fisehoana voalohany,
  // fa tsy mandeha araka ny localStorage (izay tsy hain'ny server
  // vakiana) intsony.
  initialLang?: Lang
}) {
  const [lang, setLangState] = useState<Lang>(initialLang ?? 'en')

  // Restore saved language on mount (client-only — localStorage isn't
  // available during server-side rendering). Io dia fallback ihany
  // raha misy fisehoana efa nisy tao amin'ny localStorage taloha fa
  // tsy mbola voasoratra tao amin'ny cookie (ex: session taloha).
  useEffect(() => {
    if (initialLang) return // efa marina ilay lang avy amin'ny server, tsy ilaina intsony
    try {
      const saved = localStorage.getItem('ch-lang') as Lang | null
      if (saved === 'en' || saved === 'fr') setLangState(saved)
    } catch {}
  }, [initialLang])

  const setLang = useCallback((l: Lang) => {
    setLangState(l)
    try { localStorage.setItem('ch-lang', l) } catch {}
    // Cookie 1 taona — io no vakian'ny server (app/layout.tsx) mba
    // hametrahana ny <html lang> marina amin'ny SSR manaraka.
    try {
      document.cookie = `ch-lang=${l}; path=/; max-age=31536000; SameSite=Lax`
    } catch {}
  }, [])

  const t = useCallback((key: string): string => {
    const dict = DICT[lang] as Record<string, string>
    return dict[key] ?? (DICT.en as Record<string, string>)[key] ?? ''
  }, [lang])

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  )
}

export function useLang() {
  return useContext(LangContext)
}
